<?php

$design_words = [
    //Pozytywne słowa
    //----------------------------------------------
    'stylish' => '1.5',           // Stylowy
    'sleek' => '1.5',             // Gładki
    'modern' => '1.5',            // Nowoczesny
    'elegant' => '1.5',           // Elegancki
    'sophisticated' => '2.0',     // Wyrafinowany
    'trendy' => '1.5',            // Trendy
    'chic' => '1.5',              // Elegancki
    'fashionable' => '1.5',       // Modny
    'classy' => '1.5',            // Klasyczny
    'contemporary' => '1.5',      // Współczesny
    'unique' => '1.5',            // Unikalny
    'innovative' => '1.5',        // Innowacyjny
    'creative' => '1.5',          // Kreatywny
    'original' => '1.5',          // Oryginalny
    'eye-catching' => '1.5',      // Przyciągający wzrok
    'minimalist' => '1.5',        // Minimalistyczny
    'futuristic' => '1.5',        // Futurystyczny
    'aesthetic' => '1.5',         // Estetyczny
    'luxurious' => '2.0',         // Luksusowy
    'ornate' => '1.5',            // Ozdobny
    'beautiful' => '1.5',         // Piękny
    'gorgeous' => '1.5',          // Wspaniały
    'pleasing' => '1.5',          // Miły dla oka
    'attractive' => '1.5',        // Atrakcyjny
    'appealing' => '1.5',         // Pociągający
    'graceful' => '1.5',          // Pełen wdzięku
    'satisfying' => '1.5',        // Satysfakcjonujący
    'polished' => '1.5',          // Wyrafinowany
    'streamlined' => '1.5',       // Uproszczony
    'slick' => '1.5',             // Zgrabny
    'sharp' => '1.5',             // Ostry
    'clean' => '1.5',             // Czysty
    'crisp' => '1.5',             // Świeży
    'refined' => '1.5',           // Refined
    'dazzling' => '1.5',          // Oślepiający
    'dynamic' => '1.5',           // Dynamiczny
    'vibrant' => '1.5',           // Dynamiczny
    'bold' => '1.5',              // Śmiały
    'vivid' => '1.5',             // Żywy
    'bright' => '1.5',            // Jasny
    'colorful' => '1.5',          // Kolorowy
    'playful' => '1.5',           // Zwiewny
    'joyful' => '1.5',            // Radosny
    'fun' => '1.5',               // Zabawny
    'lively' => '1.5',            // Ożywiony
    'animated' => '1.5',          // Animowany
    'interesting' => '1.5',       // Interesujący
    'captivating' => '1.5',       // Porywający
    'engaging' => '1.5',          // Angażujący
    'stimulating' => '1.5',       // Stymulujący
    'inspiring' => '1.5',         // Inspirujący
    'imaginative' => '1.5',       // Wyobraźniowy
    'artistic' => '1.5',          // Artystyczny
    'visionary' => '1.5',         // Wizjonerski
    'provocative' => '1.5',       // Prowokujący
    'thought-provoking' => '1.5', // Zmuszający do myślenia
    'unconventional' => '1.5',    // Nietypowy
    'quirky' => '1.5',            // Dziwaczny
    'eccentric' => '1.5',         // Excentryczny
    'individual' => '1.5',        // Indywidualny
    'exclusive' => '1.5',         // Wyłączny
    'distinctive' => '1.5',       // Charakterystyczny
    'special' => '1.5',           // Specjalny
    'different' => '1.5',         // Inny
    'extraordinary' => '2.0',     // Nadzwyczajny
    'original' => '1.5',          // Oryginalny
    'one-of-a-kind' => '1.5',     // Jedyny w swoim rodzaju
    'groundbreaking' => '2.0',    // Przełomowy
    'revolutionary' => '2.0',     // Rewolucyjny
    'innovative' => '1.5',        // Innowacyjny
    'trailblazing' => '2.0',      // Nowator
    'pioneering' => '2.0',        // Pionierski
    'cutting-edge' => '2.0',      // Nowoczesny
    'avant-garde' => '2.0',       // Awangardowy
    'progressive' => '1.5',       // Postępowy
    'forward-thinking' => '1.5',  // Myślący progresywnie
    'visionary' => '1.5',         // Wizjonerski
    'experimental' => '1.5',      // Eksperymentalny
    'imaginative' => '1.5',       // Wyobraźniowy
    'creative' => '1.5',          // Kreatywny
    'artistic' => '1.5',          // Artystyczny
    'artful' => '1.5',            // Zręczny
    'expressive' => '1.5',        // Ekspresyjny
    'inspiring' => '1.5',         // Inspirujący
    'inspired' => '1.5',          // Zainspirowany
    'ingenious' => '1.5',         // Genialny
    'inventive' => '1.5',         // Pomysłowy
    'clever' => '1.5',            // Sprytny
    'smart' => '1.5',             // Inteligentny
    'ingenious' => '1.5',         // Genialny
    'sophisticated' => '2.0',     // Wyrafinowany
    'slick' => '1.5',             // Zgrabny
    'neat' => '1.5',              // Schludny
    'tidy' => '1.5',              // Porządny
    'well-organized' => '1.5',    // Dobrze zorganizowany
    'orderly' => '1.5',           // Uporządkowany
    'structured' => '1.5',        // Ustrukturyzowany
    'meticulous' => '1.5',        // Skrupulatny
    'precise' => '1.5',           // Precyzyjny
    'accurate' => '1.5',          // Dokładny
    'sharp' => '1.5',             // Ostry
    'clean-cut' => '1.5',         // Czysty
    'sleek' => '1.5',             // Gładki
    'smooth' => '1.5',            // Gładki
    'flowing' => '1.5',           // Płynny
    'dynamic' => '1.5',           // Dynamiczny
    'fluid' => '1.5',             // Płynny
    'graceful' => '1.5',          // Pełen wdzięku
    'elegant' => '1.5',           // Elegancki
    'chic' => '1.5',              // Szykowny
    'fashionable' => '1.5',       // Modny
    'trendy' => '1.5',            // Trendy
    'hip' => '1.5',               // Modny
    'cool' => '1.5',              // Cool
    'tasteful' => '1.5',          // Gustowny
    'classy' => '1.5',            // Klasyczny
    'timeless' => '1.5',          // Ponadczasowy
    'refined' => '1.5',           // Refined
    'polished' => '1.5',          // Polished
    'cultivated' => '1.5',        // Uprawiany
    'cultured' => '1.5',          // Kulturalny
    'artistic' => '1.5',          // Artystyczny
    'inspiring' => '1.5',         // Inspirujący
    'captivating' => '1.5',       // Porywający
    'intriguing' => '1.5',        // Intrygujący
    'engaging' => '1.5',          // Angażujący
    'enchanting' => '1.5',        // Czarujący
    'alluring' => '1.5',          // Kuszący
    'bewitching' => '1.5',        // Oczarowujący
    'charming' => '1.5',          // Uroczy
    'endearing' => '1.5',         // Uroczy
    'lovely' => '1.5',            // Uroczy
    'delightful' => '1.5',        // Rozkoszny
    'appealing' => '1.5',         // Pociągający
    'attractive' => '1.5',        // Atrakcyjny
    'fascinating' => '1.5',       // Fascynujący
    'mesmerizing' => '1.5',       // Hipnotyzujący
    'hypnotic' => '1.5',          // Hipnotyzujący
    'ravishing' => '1.5',         // Zachwycający
    'stunning' => '1.5',          // Oszałamiający
    'breathtaking' => '1.5',      // Zapierający dech
    'awe-inspiring' => '1.5',     // Godny podziwu
    'splendid' => '1.5',          // Wspaniały
    'majestic' => '1.5',          // Majestatyczny
    'glorious' => '1.5',          // Chluba
    'grand' => '1.5',             // Wielki
    'epic' => '1.5',              // Epicki
    'legendary' => '1.5',         // Legendarny
    'mythical' => '1.5',          // Mitologiczny
    'fantastic' => '1.5',         // Fantastyczny
    'amazing' => '1.5',           // Niesamowity
    'wonderful' => '1.5',         // Cudowny
    'excellent' => '1.5',         // Doskonały
    'remarkable' => '1.5',        // Godny uwagi
    'phenomenal' => '1.5',        // Fenomenalny
    'outstanding' => '1.5',       // Wybitny
    'superb' => '1.5',            // Doskonały
    'awesome' => '1.5',           // Niesamowity
    'terrific' => '1.5',          // Wspaniały
    'fabulous' => '1.5',          // Fantastyczny
    'brilliant' => '1.5',         // Błyskotliwy
    'marvelous' => '1.5',         // Cudowny
    'extraordinary' => '2.0',     // Nadzwyczajny
    'miraculous' => '2.0',        // Cudowny
    'jaw-dropping' => '2.0',      // Otwierający usta
    'mind-blowing' => '2.0',      // Niewiarygodny
    'stunning' => '1.5',          // Oszałamiający
    'gobsmacking' => '2.0',       // Oderwany od zmysłów
    'astounding' => '2.0',        // Zdumiewający
    'unbelievable' => '2.0',      // Niewiarygodny
    'incredible' => '2.0',        // Niewiarygodny
    'fantabulous' => '1.5',       // Fantastyczny
    'mind-boggling' => '2.0',     // Oszałamiający
    'magnificent' => '1.5',       // Wspaniały
    'jaw-dropping' => '2.0',      // Otwierający usta
    'eye-popping' => '1.5',       // Oczywisty
    'awe-inspiring' => '1.5',     // Godny podziwu
    'breathtaking' => '1.5',      // Zapierający dech
    'spellbinding' => '1.5',      // Oczarowujący
    'sensational' => '1.5',       // Sensacyjny
    'captivating' => '1.5',       // Porywający
    'enchanting' => '1.5',        // Czarujący
    'enticing' => '1.5',          // Kuszący
    'alluring' => '1.5',          // Pociągający
    'charismatic' => '1.5',       // Charyzmatyczny
    'appealing' => '1.5',         // Pociągający
    'tempting' => '1.5',          // Kuszący
    'irresistible' => '1.5',      // Nieodparty
    'fascinating' => '1.5',       // Fascynujący
    'mesmerizing' => '1.5',       // Hipnotyzujący
    'hypnotic' => '1.5',          // Hipnotyzujący
    'compelling' => '1.5',        // Porywający
    'gripping' => '1.5',          // Porywający
    'absorbing' => '1.5',         // Wchłaniający
    'engrossing' => '1.5',        // Porywający
    'engaging' => '1.5',          // Angażujący
    'riveting' => '1.5',          // Porywający
    'intriguing' => '1.5',        // Intrygujący
    'enthralling' => '1.5',       // Ujmujący
    'delightful' => '1.5',        // Rozkoszny
    'pleasant' => '1.0',          // Przyjemny
    'enjoyable' => '1.0',         // Przyjemny
    'pleasurable' => '1.0',       // Przyjemny
    'agreeable' => '1.0',         // Miły
    'comfortable' => '1.0',       // Wygodny
    'cozy' => '1.0',              // Przytulny
    'inviting' => '1.0',          // Zapraszający
    'homely' => '1.0',            // Domowy
    //Negatywne słowa
    //----------------------------------------------------
    'ugly' => '-2.0',                // Brzydki
    'unattractive' => '-1.5',        // Nieatrakcyjny
    'unappealing' => '-1.5',         // Niekuszący
    'unappealing' => '-1.5',         // Niekuszący
    'dated' => '-1.5',               // Przestarzały
    'outdated' => '-1.5',            // Przestarzały
    'dull' => '-1.5',                // Nudny
    'bland' => '-1.5',               // Nijaki
    'uninspired' => '-1.5',          // Niekreatywny
    'uninspiring' => '-1.5',         // Niekreatywny
    'uninteresting' => '-1.5',       // Nudny
    'plain' => '-1.5',               // Zwyczajny
    'mediocre' => '-1.5',            // Przeciętny
    'ordinary' => '-1.5',            // Zwyczajny
    'average' => '-1.5',             // Przeciętny
    'basic' => '-1.5',               // Podstawowy
    'unremarkable' => '-1.5',        // Niewyróżniający się
    'forgettable' => '-1.5',         // Łatwo zapominany
    'cheap' => '-2.0',               // Tani
    'low-quality' => '-2.0',         // Niskiej jakości
    'poorly-made' => '-2.0',         // Słabo wykonany
    'shoddy' => '-2.0',              // Niedbały
    'flimsy' => '-2.0',              // Nieduży
    'fragile' => '-2.0',             // Kruchy
    'delicate' => '-1.5',            // Delikatny
    'weak' => '-1.5',                // Słaby
    'unstable' => '-1.5',            // Niestabilny
    'unreliable' => '-2.0',          // Niewiarygodny
    'untrustworthy' => '-2.0',       // Niegodny zaufania
    'unsteady' => '-1.5',            // Niestały
    'inconsistent' => '-1.5',        // Niespójny
    'subpar' => '-2.0',              // Poniżej standardu
    'inferior' => '-2.0',            // Gorszy
    'faulty' => '-2.0',              // Wadliwy
    'defective' => '-2.0',           // Wadliwy
    'broken' => '-2.0',              // Zepsuty
    'damaged' => '-2.0',             // Uszkodzony
    'scratched' => '-2.0',           // Porysowany
    'worn' => '-1.5',                // Zużyty
    'dated' => '-1.5',               // Przestarzały
    'outmoded' => '-1.5',            // Przestarzały
    'obsolete' => '-2.0',            // Przestarzały
    'out-of-date' => '-1.5',         // Przestarzały
    'unfashionable' => '-1.5',       // Nie modny
    'unstylish' => '-1.5',           // Nie stylowy
    'tacky' => '-2.0',               // Kiczowaty
    'gaudy' => '-2.0',               // Wyszydzający
    'tasteless' => '-2.0',           // Bezwzględny
    'hideous' => '-2.0',             // Obrzydliwy
    'repulsive' => '-2.0',           // Odpychający
    'unsightly' => '-2.0',           // Brzydki
    'unattractive' => '-1.5',        // Nieatrakcyjny
    'uninviting' => '-1.5',          // Niepociągający
    'unappealing' => '-1.5',         // Niekuszący
    'unpleasant' => '-1.5',          // Nieprzyjemny
    'unpleasant-looking' => '-1.5',  // Brzydki wygląd
    'unpleasant-appearing' => '-1.5', // Nieprzyjemny wygląd
    'unpleasant-to-look-at' => '-1.5', // Nieprzyjemne dla oka
    'harsh' => '-1.5',               // Szorstki
    'clashing' => '-1.5',            // Kontrastujący
    'uncoordinated' => '-1.5',       // Nieskoordynowany
    'chaotic' => '-1.5',             // Chaotyczny
    'disorganized' => '-1.5',        // Nieskładny
    'messy' => '-1.5',               // Zabałaganiony
    'jumbled' => '-1.5',             // Zmieszany
    'cluttered' => '-1.5',           // Zagracony
    'awkward' => '-1.5',             // Niezręczny
    'uncomfortable' => '-1.5',       // Niewygodny
    'ill-fitting' => '-1.5',         // Niepasujący
    'unwieldy' => '-1.5',            // Nieporęczny
    'bulky' => '-1.5',               // Masywny
    'cumbersome' => '-1.5',          // Niewygodny
    'clumsy' => '-1.5',              // Niezdarny
    'unsophisticated' => '-1.5',     // Niewyszukany
    'tacky' => '-2.0',               // Kiczowaty
    'vulgar' => '-2.0',              // Wulgarny
    'gaudy' => '-2.0',               // Wyszydzający
    'tasteless' => '-2.0',           // Bezwzględny
    'kitschy' => '-2.0',             // Kiczowaty
    'trashy' => '-2.0',              // Nędzny
    'cheesy' => '-2.0',              // Banalny
    'garish' => '-2.0',              // Jaskrawy
    'loud' => '-1.5',                // Głośny
    'over-the-top' => '-1.5',        // Przesadzony
    'overdone' => '-1.5',            // Przesadzony
    'tasteless' => '-2.0',           // Bezwzględny
    'unsuitable' => '-1.5',          // Niewłaściwy
    'inappropriate' => '-1.5',       // Nieodpowiedni
    'unfitting' => '-1.5',           // Nieodpowiedni
    'wrong' => '-1.5',               // Nieodpowiedni
    'incongruous' => '-1.5',         // Niespójny
    'mismatched' => '-1.5',          // Niepasujący
    'misfitting' => '-1.5',          // Niepasujący
    'unmatched' => '-1.5',           // Niepasujący
    'dissonant' => '-1.5',           // Dźwięczny
    'discordant' => '-1.5',          // Dźwięczny
    'clashing' => '-1.5',            // Kontrastujący
    'conflicting' => '-1.5',         // Sprzeczny
    'inharmonious' => '-1.5',        // Nieharmonijny
    'jarring' => '-1.5',             // Drażniący
    'dissapointing' => '-1.5'
];

?>