<?php

$durability_words = [
    'durable' => '1.5',         // Bardzo trwały
    'sturdy' => '1.5',          // Wytrzymały
    'resilient' => '1.5',       // Odporny
    'robust' => '1.5',          // Solidny
    'tough' => '1.5',           // Twardy
    'long-lasting' => '1.5',    // Długotrwały
    'enduring' => '1.5',        // Wytrzymały
    'strong' => '1.5',          // Silny
    'reliable' => '1.5',        // Niezawodny
    'sturdy' => '1.5',          // Solidny
    'steadfast' => '1.5',       // Wierny
    'firm' => '1.5',            // Stabilny
    'hard-wearing' => '1.5',    // Wytrzymały na zużycie
    'indestructible' => '2.0',  // Niezniszczalny
    'unbreakable' => '2.0',     // Niezniszczalny
    'heavy-duty' => '2.0',      // Odporny na obciążenie
    'impervious' => '2.0',      // Nieprzepuszczalny
    'invincible' => '2.0',      // Niezwyciężony
    'unyielding' => '2.0',      // Nieustępliwy
    'bulletproof' => '2.0',     // Kuloodporny
    'unbending' => '1.5',       // Niewzruszony
    'unsurpassable' => '2.0',   // Nie do przebicia
    'faultless' => '1.5',       // Bezusterkowy
    'flawless' => '1.5',        // Bez skazy
    'great' => '1.0',
    'perfect' => '1.5',         // Doskonały
    'ideal' => '1.5',           // Idealny
    'excellent' => '1.5',       // Doskonały
    'first-rate' => '1.5',      // Pierwszorzędny
    'premium' => '1.5',         // Premium
    'high-quality' => '1.5',    // Wysokiej jakości
    'exceptional' => '1.5',     // Wyjątkowy
    'extraordinary' => '2.0',   // Nadzwyczajny
    'superior' => '1.5',        // Wybitny
    'elite' => '1.5',           // Elitarny
    'outstanding' => '1.5',     // Wybitny
    'splendid' => '1.5',        // Wspaniały
    'exemplary' => '1.5',       // Przykładowy
    'unparalleled' => '2.0',    // Niezrównany
    'unmatched' => '2.0',       // Niezrównany
    'unsurpassed' => '2.0',     // Niezrównany
    'incomparable' => '2.0',    // Niezrównany
    'unrivaled' => '2.0',       // Niezrównany
    'beyond compare' => '2.0',  // Niezrównany
    'unexcelled' => '2.0',      // Niezrównany
    'peerless' => '2.0',        // Niezrównany
    'inimitable' => '2.0',      // Niezrównany
    'unexampled' => '2.0',      // Niezrównany
    'unique' => '1.5',          // Unikalny
    'indefectible' => '1.5',    // Nieskazitelny
    'unimpeachable' => '1.5',   // Niepodważalny
    'irreproachable' => '1.5',  // Nienaganny
    'consummate' => '1.5',      // Doskonały
    'supreme' => '1.5',         // Najwyższy
    'ultimate' => '1.5',        // Ostateczny
    'unassailable' => '2.0',    // Niepodważalny
    'impeccable' => '1.5',      // Nieskazitelny
    'faultless' => '1.5',       // Bezbłędny
    'matchless' => '2.0',       // Niezrównany
    'unfailing' => '1.5',       // Niezawodny
    'immaculate' => '1.5',      // Nieskazitelny
    'perfect' => '1.5',         // Idealny
    'faultless' => '1.5',       // Bezusterkowy
    'flawless' => '1.5',        // Bez skazy
    'untarnished' => '1.5',     // Nieskazitelny
    'unspoiled' => '1.5',       // Nieskażony
    'unmarred' => '1.5',        // Nienaruszony
    'unsullied' => '1.5',       // Nieskażony
    'impeccable' => '1.5',      // Nieskazitelny
    'excellent' => '1.5',       // Doskonały
    'unsurpassable' => '2.0',   // Nie do przebicia
    'unblemished' => '1.5',     // Nieskazitelny
    'unhurt' => '1.5',          // Nienaruszony
    'unharmed' => '1.5',        // Nienaruszony
    'unscathed' => '1.5',       // Nienaruszony
    'uninjured' => '1.5',       // Nienaruszony
    'unscratched' => '1.5',     // Nieporysowany
    'unflawed' => '1.5',        // Nieskazitelny
    'undefiled' => '1.5',       // Nieskażony
    'intact' => '1.5',          // Nietknięty
    'unbroken' => '1.5',        // Nienaruszony
    'undamaged' => '1.5',       // Nieuszkodzony
    'sound' => '1.5',           // Nienaruszony
    'unimpaired' => '1.5',      // Nienaruszony
    'undiminished' => '1.5',    // Nienaruszony
    'unspoiled' => '1.5',       // Nieskażony
'unspoilt' => '1.5',        // Nieskażony
'untouched' => '1.5',       // Nietknięty
'uninfluenced' => '1.5',    // Nienaruszony
'unaltered' => '1.5',       // Nienaruszony
'undisturbed' => '1.5',     // Nienaruszony
'unaffected' => '1.5',      // Nienaruszony
'unhurt' => '1.5',          // Nienaruszony
'unharmed' => '1.5',        // Nienaruszony
'unscathed' => '1.5',       // Nienaruszony
'uninjured' => '1.5',       // Nienaruszony
'unscratched' => '1.5',     // Nieporysowany
'unflawed' => '1.5',        // Nieskazitelny
'undefiled' => '1.5',       // Nieskażony
'intact' => '1.5',          // Nietknięty
'unbroken' => '1.5',        // Nienaruszony
'undamaged' => '1.5',       // Nieuszkodzony
'sound' => '1.5',           // Nienaruszony
'unimpaired' => '1.5',      // Nienaruszony
'undiminished' => '1.5',    // Nienaruszony
'fault-tolerant' => '1.5',  // Odporny na błędy
'defect-free' => '1.5',     // Bez wad
'wear-resistant' => '1.5',  // Odporny na zużycie
'antiwear' => '1.5',        // Odporny na zużycie
'wear-proof' => '1.5',      // Odporny na zużycie
'sturdy' => '1.5',          // Solidny
'built to last' => '1.5',   // Zbudowany aby przetrwać
'heavy-duty' => '2.0',      // Odporny na obciążenie
'bulletproof' => '2.0',     // Kuloodporny
'impervious' => '2.0',      // Nieprzepuszczalny
'unbreakable' => '2.0',     // Niezniszczalny
'indestructible' => '2.0',  // Niezniszczalny
'unyielding' => '2.0',      // Nieustępliwy
'unassailable' => '2.0',    // Niepodważalny
'unparalleled' => '2.0',    // Niezrównany
'unmatched' => '2.0',       // Niezrównany
'unsurpassed' => '2.0',     // Niezrównany
'incomparable' => '2.0',    // Niezrównany
'unrivaled' => '2.0',       // Niezrównany
'beyond compare' => '2.0',  // Niezrównany
'unexcelled' => '2.0',      // Niezrównany
'peerless' => '2.0',        // Niezrównany
'inimitable' => '2.0',      // Niezrównany
'unexampled' => '2.0',      // Niezrównany
'unmatched' => '2.0',       // Niezrównany
'unsurpassed' => '2.0',     // Niezrównany
'unrivaled' => '2.0',       // Niezrównany
'beyond compare' => '2.0',  // Niezrównany
'unexcelled' => '2.0',      // Niezrównany
'peerless' => '2.0',        // Niezrównany
'inimitable' => '2.0',      // Niezrównany
'unexampled' => '2.0',      // Niezrównany
'unique' => '1.5',          // Unikalny
'superlative' => '1.5',     // Najwyższej jakości
'unsurmountable' => '2.0',  // Nie do pokonania
'unconquerable' => '2.0',   // Nie do zdobycia
'insuperable' => '2.0',     // Nie do przezwyciężenia
'unflagging' => '1.5',       // Wytrwały
'untiring' => '1.5',         // Niewzmocniony
'unwearying' => '1.5',       // Niezmordowany
'unfaltering' => '1.5',      // Niezachwiany
'unwavering' => '1.5',       // Niezachwiany
'unswerving' => '1.5',       // Niezachwiany
'unyielding' => '2.0',       // Nieustępliwy
'unshakable' => '1.5',       // Niezachwiany
'unmoveable' => '1.5',       // Niezachwiany
'unshakeable' => '1.5',      // Niezachwiany
'unshaken' => '1.5',         // Niezachwiany
'unbending' => '1.5',        // Nieustępliwy
'unswerving' => '1.5',       // Niezachwiany
'uncompromising' => '1.5',   // Nieustępliwy
'unflinching' => '1.5',      // Niezachwiany
'unhesitating' => '1.5',     // Niezwłoczny
'unvarying' => '1.5',        // Nieszablonowy
'unwavering' => '1.5',       // Niezachwiany
'unrelenting' => '1.5',      // Nieustępliwy
'unbowed' => '1.5',          // Niepodległy
'unshifting' => '1.5',       // Nieustępliwy
'unmovable' => '1.5',        // Niezachwiany
'unperturbed' => '1.5',      // Niezakłócony
'unmoved' => '1.5',           // Niezakłócony
'steadfast' => '1.5',         // Wierny
'resolute' => '1.5',          // Stanowczy
'determined' => '1.5',        // Zdecydowany
'firm' => '1.5',              // Stabilny
'constant' => '1.5',          // Stały
'stable' => '1.5',            // Stabilny
'unwavering' => '1.5',        // Niezachwiany
'assured' => '1.5',           // Pewny siebie
'unshakable' => '1.5',        // Niezachwiany
'undoubted' => '1.5',         // Niekwestionowany
'unquestioned' => '1.5',      // Niekwestionowany
'fixed' => '1.5',              // Stały
'immovable' => '1.5',          // Niezachwiany
'unbending' => '1.5',          // Nieustępliwy
'adamant' => '1.5',            // Nieugięty
'unyielding' => '2.0',         // Nieustępliwy
'uncompromising' => '1.5',     // Nieustępliwy
'rigid' => '1.5',              // Sztywny
'unchanging' => '1.5',         // Niewzruszony
'fixed' => '1.5',               // Stały
'immutable' => '1.5',          // Niezmienny
'inflexible' => '1.5',         // Niedający się wyginać
'resistant' => '1.5',           // Odporny
'unconquerable' => '2.0',       // Nie do zdobycia
'indomitable' => '2.0',         // Niezdobyty
'unflinching' => '1.5',         // Niezachwiany
'unhesitating' => '1.5',        // Niezwłoczny
'valiant' => '1.5',             // Dzielny
'heroic' => '1.5',              // Heroiczny
'fearless' => '1.5',            // Nieustraszony
'undaunted' => '1.5',           // Niezłomny
'courageous' => '1.5',          // Odważny
'bold' => '1.5',                 // Śmiały
'unintimidated' => '1.5',       // Niezrażony
'unshaken' => '1.5',             // Niezachwiany
'unmoved' => '1.5',               // Niezakłócony
'unaffected' => '1.5',            // Nienaruszony
'uninfluenced' => '1.5',          // Nienaruszony
'unimpressed' => '1.5',            // Niewzruszony
'undaunted' => '1.5',               // Niezłomny
'unfazed' => '1.5',                  // Niezrażony
'unruffled' => '1.5',                 // Niewzruszony
'impervious' => '2.0',                // Nieprzepuszczalny
'invulnerable' => '2.0',             // Niepodatny na uszkodzenia
'unaffected' => '1.5',                  // Nienaruszony
'unhurt' => '1.5',                 // Nienaruszony
'unharmed' => '1.5',                // Nienaruszony
'unscathed' => '1.5',                  // Nienaruszony
'uninjured' => '1.5',                    // Nienaruszony
'unbruised' => '1.5',                      // Niepobity
'unwounded' => '1.5',                         // Niezraniony
'untouched' => '1.5',                            // Nietknięty
'untainted' => '1.5',                               // Nieskażony
'unspoiled' => '1.5',                                    // Nieskażony
'unhindered' => '1.5',                                       // Nieograniczony
'unrestricted' => '1.5',                                        // Nieograniczony
'unlimited' => '1.5',                                             // Nieograniczony
'boundless' => '1.5',                                                // Nieograniczony
'endless' => '1.5',                                                     // Nieograniczony
'limitless' => '1.5',                                                       // Nieograniczony
'inexhaustible' => '1.5',                                                    // Niewyczerpany
'bottomless' => '1.5',                             // Bez dna
'boundless' => '1.5',                                       // Bezgraniczny
'unbounded' => '1.5',                                          // Bezgraniczny
'vast' => '1.5',                                                      // Ogromny
'immeasurable' => '1.5',         // Niezmierzalny
'immense' => '1.5',                 // Ogromny
'infinite' => '1.5',                      // Nieskończony
'enormous' => '1.5',                          // Ogromny
'massive' => '1.5',                              // Masywny
'tremendous' => '1.5',                               // Ogromny
'gigantic' => '1.5',                                   // Gigantyczny
'mammoth' => '1.5',                                            // Mamuci
'colossal' => '1.5',                                               // Kolosalny
'gargantuan' => '1.5',          //Ogromny
'huge' => '1.5',                // // Ogromny
'giant' => '1.5',               //                 // Gigantyczny
'titanic' => '1.5',             //                       // Tytaniczny
'mountainous' => '1.5',
'indestructible' => '2.0',      // Niezniszczalny
'unbreakable' => '2.0',          // Niezniszczalny
'impregnable' => '2.0',           // Nie do zdobycia
'invincible' => '2.0',            // Niezwyciężony
'unbeatable' => '2.0',             // Niepokonany
'unconquerable' => '2.0',          // Niepokonany
'unassailable' => '2.0',            // Niepodważalny
'unyielding' => '2.0',                // Nieustępliwy
'unshakable' => '1.5',                 // Niezachwiany
'unwavering' => '1.5',                   // Niezachwiany
'unflinching' => '1.5',                     // Niezachwiany
'firm' => '1.5',                              // Stabilny
'steady' => '1.5',                              // Stały
'stable' => '1.5',                                 // Stabilny
'resolute' => '1.5',                                 // Stanowczy
'unfaltering' => '1.5',                                 // Niezachwiany
'robust' => '1.5',                                      // Solidny
'strong' => '1.5',                                        // Silny
'vigorous' => '1.5',                                       // Energiczny
'forceful' => '1.5',                                         // Potężny
'tough' => '1.5',                                              // Twardy
'hardy' => '1.5',                                                // Wytrzymały
'durable' => '1.5',                                                  // Trwały
'resilient' => '1.5',                                                    // Elastyczny
'enduring' => '1.5',                                                       // Wytrzymały
'reliable' => '1.5',                                                           // Niezawodny
'indestructible' => '2.0',                                                     // Niezniszczalny
'unbreakable' => '2.0',                                                           // Niezniszczalny
'heavy-duty' => '2.0',                                                                // Odporny na obciążenie
'impervious' => '2.0',                                                                    // Nieprzepuszczalny
'invincible' => '2.0',                                                                       // Niezwyciężony
'unbeatable' => '2.0',                                                                           // Niepokonany
'unconquerable' => '2.0',                                                                            // Niepokonany
'unassailable' => '2.0',                                                                                // Niepodważalny
'unyielding' => '2.0',                                                                                     // Nieustępliwy
'unshakable' => '1.5',                                                                                        // Niezachwiany
'unwavering' => '1.5',    //Niezachwiany
'unflinching' => '1.5',     // Niezachwiany
'adamant' => '1.5',            // Nieugięty
'boundless' => '1.5',               // Bezgraniczny
'unbounded' => '1.5',                     // Bezgraniczny
'immense' => '1.5',                           // Ogromny
'infinite' => '1.5',                                 // Nieskończony
'enormous' => '1.5',                                       // Ogromny
'massive' => '1.5',                                              // Masywny
'tremendous' => '1.5',                                                 // Ogromny
'gigantic' => '1.5',                                                        // Gigantyczny
'monumental' => '1.5',                                                             // Monumentalny
'mammoth' => '1.5',                                                                    // Mamuci
'colossal' => '1.5',                                                                        // Kolosalny
'gargantuan' => '1.5',                                                                          // Ogromny
'huge' => '1.5',                                                                                    // Ogromny
'enormous' => '1.5',                                                                                        // Ogromny
'immense' => '1.5',                                                                                                // Ogromny
'giant' => '1.5',                                                                                                        // Gigantyczny
'titanic' => '1.5',                                                                                                            // Tytaniczny
'mountainous' => '1.5',                                                                                                                  // Górski
'unlimited' => '1.5',                                                                                                                          // Nieograniczony
'inexhaustible' => '1.5',                                                                                                                                // Niewyczerpany
'bottomless' => '1.5',                                                                                                                                        // Bez dna
'indomitable' => '2.0',                                                                                                                                               // Niezdobyty
'unbeatable' => '2.0',                                                                                                                                                       // Niepokonany
'unassailable' => '2.0',                                                                                                                                                            // Niepodważalny
'unyielding' => '2.0',                                                                                                                                                                      // Nieustępliwy
'impregnable' => '2.0',                                                                                                                                                                               // Nie do zdobycia
'invincible' => '2.0',                                                                                                                                                                                       // Niezwyciężony
'unconquerable' => '2.0',                                                                                                                                                                                           // Niepokonany
'indestructible' => '2.0',                                                                                                                                                                                               // Niezniszczalny
'unbreakable' => '2.0',                                                                                                                                                                                                       // Niezniszczalny
'heavy-duty' => '2.0',                                                                                                                                                                                                             // Odporny na obciążenie
'bulletproof' => '2.0',                                                                                                                                                                                                                 // Kuloodporny
'impervious' => '2.0',                                                                                                                                                                                                                       // Nieprzepuszczalny
'unbending' => '1.5',                                                                                                                                                                                                                                 // Nieustępliwy
'unsurpassable' => '2.0',                                                                                                                                                                                                                                        // Nie do przebicia
'unmatched' => '2.0',                                                                                                                                                                                                                                                  // Niezrównany
'unsurpassed' => '2.0',                                                                                                                                                                                                                                                        // Niezrównany
'incomparable' => '2.0',                                                                                                                                                                                                                                                                 // Niezrównany
'unrivaled' => '2.0',                                                                                                                                                                                                                                                                            // Niezrównany
'beyond compare' => '2.0',                                                                                                                                                                                                                                                                                      // Niezrównany
'unexcelled' => '2.0'  ,  

//Negatywne
//---------------------------------------
'fragile' => '-2.0', // kruchy, łamliwy
'weak' => '-2.0', // słaby
'delicate' => '-2.0', // delikatny
'flimsy' => '-2.0', // chwiejny, wątły
'brittle' => '-2.0', // kruchy, łamliwy
'vulnerable' => '-2.0', // podatny, wrażliwy
'breakable' => '-2.0', // łamliwy, nadający się do zniszczenia
'susceptible' => '-2.0', // podatny, wrażliwy
'sensitive' => '-2.0', // wrażliwy, czuły
'tender' => '-2.0', // delikatny, miękki
'frail' => '-2.0', // kruchy, słaby
'crumbly' => '-2.0', // kruszący się
'easily damaged' => '-2.0', // łatwo ulegający uszkodzeniom
'unstable' => '-2.0', // niestabilny
'wobbly' => '-2.0', // chwiejny, chybotliwy
'shaky' => '-2.0', // chwiejny, drżący
'rickety' => '-2.0', // chwiejny, wątły
'insecure' => '-2.0', // niepewny, niestabilny
'feeble' => '-2.0', // słaby, mizerny
'decayed' => '-2.0', // zgniły, zepsuty
'deteriorating' => '-2.0', // pogarszający się, degradujący
'perishable' => '-2.0', // nietrwały, łatwo psujący się
'decomposing' => '-2.0', // rozkładający się, gnicie
'eroding' => '-2.0', // erodujący, niszczący
'corroded' => '-2.0', // skorodowany, zardzewiały
'ephemeral' => '-2.0', // ulotny, przemijający
'transient' => '-2.0', // przemijający, chwilowy
'temporary' => '-2.0', // tymczasowy, przejściowy
'short-lived' => '-2.0', // krótkotrwały
'failing' => '-2.0', // słabnący, nieudolny
'weakening' => '-2.0', // osłabiający, słabnący
'degenerating' => '-2.0', // degenerujący, zanikający
'diminishing' => '-2.0', // malejący, zmniejszający się
'shrinking' => '-2.0', // kurczący się, zmniejszający się
'fading' => '-2.0', // blaknący, słabnący
'deteriorated' => '-2.0', // pogorszony, zdegradowany
'flawed' => '-2.0', // wadliwy, błędny
'damaged' => '-2.0', // uszkodzony, zniszczony
'worn-out' => '-2.0', // zużyty, wyczerpany
'tattered' => '-2.0', // podarty, sfatygowany
'ripped' => '-2.0', // podarty, rozdarty
'torn' => '-2.0', // rozdarty, podarty
'threadbare' => '-2.0', // przetarty, wytarty
'worn-down' => '-2.0', // zużyty, zdarty
'dilapidated' => '-2.0', // zniszczony, podupadły
'run-down' => '-2.0', // zniszczony, podupadły
'shabby' => '-2.0', // niechlujny, obskurny
'ramshackle' => '-2.0', // rozklekotany, rozpadający się
'battered' => '-2.0', // poturbowany, potłuczony
'beaten-up' => '-2.0', // zniszczony, poturbowany
'decrepit' => '-2.0', // rozpadający się, zrujnowany
'crumbling' => '-2.0', // rozpadający się, kruszący się
'shattered' => '-2.0', // roztrzaskany, rozbity
'smashed' => '-2.0', // rozbity, potłuczony
'demolished' => '-2.0', // zniszczony, zburzony
'ruined' => '-2.0', // zrujnowany, zniszczony
'collapsing' => '-2.0', // zapadający się, załamujący się
'falling apart' => '-2.0', // rozpadający się, rozpadać się
'defective' => '-2.0', // wadliwy, mający wady
'faulty' => '-2.0', // wadliwy, zepsuty
'blemished' => '-2.0', // wadliwy, plamiony
'impaired' => '-2.0', // uszkodzony, zaburzony
'spoiled' => '-2.0', // zepsuty, zgniły
'unsound' => '-2.0', // niesolidny, wadliwy
'unreliable' => '-2.0', // niepewny, zawodny
'unsafe' => '-2.0', // niebezpieczny, nieszybki
'hazardous' => '-2.0', // niebezpieczny, ryzykowny
'treacherous' => '-2.0', // zdradliwy, podstępny
'risky' => '-2.0', // ryzykowny, niebezpieczny
'untrustworthy' => '-2.0', // niegodny zaufania, niewiarygodny
'unsteady' => '-2.0', // niestabilny, chwiejny
'unpredictable' => '-2.0', // nieprzewidywalny, nieobliczalny
'capricious' => '-2.0', // kapryśny, przewrotny
'teetering' => '-2.0', // chwiejący się, chybotliwy
'tottering' => '-2.0', // chwiejny, kołyszący się
'wavering' => '-2.0', // chwiejny, waha się
'undependable' => '-2.0', // niepewny, zawodny
'undurable' => '-2.0', // nietrwały, kruchy
'unsubstantial' => '-2.0', // nietrwały, mało istotny
'fragility' => '-1.5', // kruchość, łamliwość
'weakness' => '-1.5', // słabość, niedoskonałość
'instability' => '-1.5', // niestabilność, chwiejność
'deterioration' => '-1.5', // pogorszenie, degradacja
'decay' => '-1.5', // rozkład, gnicie
'perishability' => '-1.5', // nietrwałość, przemijalność
'erosion' => '-1.5', // erozja, niszczenie
'corrosion' => '-1.5', // korozja, rdza
'vulnerability' => '-1.5', // podatność, wrażliwość
'impermanence' => '-1.5', // nietrwałość, przemijalność
'temporariness' => '-1.5', // tymczasowość, przejściowość
'faintness' => '-1.5', // słabość, mizerność
'diminishment' => '-1.5', // zmniejszanie się, osłabienie
'flaw' => '-1.5', // wada, defekt
'damage' => '-1.5', // szkoda, uszkodzenie
'wear' => '-1.5', // zużycie, zużywanie
'tatter' => '-1.5', // strzęp, strzępienie się
'tear' => '-1.5', // rozdzieranie, łza
'threadbareness' => '-1.5', // zniszczenie, wytarcie
'dilapidation' => '-1.5', // ruina, zniszczenie
'shabbiness' => '-1.5', // obskurność, nędza
'crumblingness' => '-1.5', // rozpad, kruszenie się
'deficiency' => '-1.5', // niedobór, brak
'imperfection' => '-1.5', // niedoskonałość, wada
'blemish' => '-1.5', // skaza, plama
'impairment' => '-1.5', // uszczerbek, upośledzenie
'spoilage' => '-1.5', // zepsucie, psucie się
'unsoundness' => '-1.5', // nietrwałość, słabość
'unreliability' => '-1.5', // niepewność, zawodność
'unsafeness' => '-1.5', // niebezpieczeństwo, ryzyko
'hazardousness' => '-1.5', // niebezpieczeństwo, ryzyko
'treachery' => '-1.5', // zdrada, podstęp
'riskiness' => '-1.5', // ryzyko, niebezpieczeństwo
'unsteadiness' => '-1.5', // niestabilność, chwiejność
'unpredictability' => '-1.5', // nieprzewidywalność, zmiennosć
'instability' => '-1.5', // niestabilność, chwiejność
'teeteriness' => '-1.5', // chwiejność, niestabilność
'totteriness' => '-1.5', // chwiejność, chybotliwość
'waveringness' => '-1.5', // chwiejność, wahanie
'undependability' => '-1.5', // niepewność, zawodność
'fragileness' => '-1.5', // kruchość, delikatność
'weaknessness' => '-1.5', // słabość, ułomność
'instabilityness' => '-1.5', // niestabilność, chwiejność
'dissapointing' => '-1.5'
];

?>